AWSTemplateFormatVersion: 2010-09-09
Parameters:
    VotingServiceStack:
        Type: String
Resources:
    VoteAPI:
        Type: AWS::ApiGateway::RestApi
        Properties:
            Name: voteAPI
    VoteAPIVoteAL:
        Type: AWS::ApiGateway::Method
        Properties:
            RestApiID:
                Ref: VoteAPI
            ResourceID:
                Ref:
                    "Fn::GetAtt":
                        - VoteAPI
                        - RootResourceId
            HttpMethod: POST
            AuthorizationType: NONE
            Integration:
                Type: AWS
                IntegrationHttpMethod: POST
                Uri:
                    "Fn::Join":
                        - ""
                        - :
                            - "arn:aws:apigateway:"
                            - Ref: "AWS::Region"
                            - ":lambda:path/2015-03-31/functions/"
                            - "Fn::GetAtt":
                                - !ImportValue:
                                    !Sub: "${VotingServiceStack}-VoteAPIFunction"
                                - Arn
                            - "/invocations"
                IntegrationResponses: TODO(joe)
                PassthroughBehavior: NEVER
                RequestTemplates: TODO(joe)
            RequestParameters: TODO(joe)
            MethodResponses: TODO(joe)
Outputs:
    ApiId:
        Value:
            Ref: VoteAPI

# TODO(joe): endpoints for AK, ..., WI, WY.

