AWSTemplateFormatVersion: 2010-09-09
Parameters:
    CodeBucket:
        Type: String
    CodeObjectKey:
        Type: String
Resources:
    VotesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: Color
                  AttributeType: S
            KeySchema:
                - AttributeName: Color
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
    VoteCountsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: Color
                  AttributeType: S
            KeySchema:
                - AttributeName: Color
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
    VotingServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName:
                    !Sub: "${AWS::StackName}-VotingServiceRole"
                  PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                        - Effect: Allow
                          Action:
                            - logs:CreateLogGroup
                            - logs:CreateLogStream
                            - logs:PutLogEvents
                          Resource:
                            - arn:aws:logs:*:*:*
                        - Effect: Allow
                          Action:
                            - dynamodb:GetItem
                            - dynamodb:PutItem
                            - dynamodb:Query
                            - dynamodb:UpdateItem
                          Resource: "*"
    VotesTriggerFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket:
                    Ref: CodeBucket
                S3Key:
                    Ref: CodeObjectKey
            Runtime: nodejs4.3
            Handler: app.services.voting.trigger
            Role:
                !GetAtt:
                    - VotingServiceRole
                    - Arn
    VoteAPIFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket:
                    Ref: CodeBucket
                S3Key:
                    Ref: CodeObjectKey
            Runtime: nodejs
            Handler: app.services.voting.vote
            Role:
                !GetAtt:
                    - VotingServiceRole
                    - Arn
Outputs:
    VoteAPIFunction:
        Value:
            Ref: VoteAPIFunction
        Export:
            Name:
                !Sub: "${AWS::StackName}-VoteAPIFunction"

